[build]
target = [
    "x86_64-canicula-kernel.json",
    "aarch64-canicula-kernel.json",
    "riscv64gc-canicula-kernel.json"
]

[unstable]
json-target-spec = true
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]